uploads = []
outputs = []

[[generated]]
id = "YdBqW6VL8vzuHdIOexVer"
uri = "file://artifacts/hawtrix/assets/images/icon.png"
type = "image"
title = "hawtrix_icon"

[[generated]]
id = "x3knHXTkuvL7uF3Q_em0W"
uri = "file://artifacts/hawtrix/assets/images/hero_banner.png"
type = "image"
title = "hero_banner"

[[generated]]
id = "O71ANJKgRhZwqr44pSSJZ"
uri = "file://artifacts/hawtrix/assets/images/splash.png"
type = "image"
title = "splash_screen"

[[generated]]
id = "C-pY7SWorIMSilaT2iCH6"
uri = "file://artifacts/hawtrix-web/public/hero-professional.png"
type = "image"
title = "African professional using mobile app"

[[generated]]
id = "mOni17UdlZi6Fo6Ls-BSN"
uri = "file://artifacts/hawtrix-web/public/team-collaboration.png"
type = "image"
title = "African professionals collaborating in modern office"
