# Dans le dossier du projet téléchargé
git init
git add .
git commit -m "feat: paiement Paygate Global TMoney/Flooz"
git branch -M main
git remote add origin https://github.com/Hawtrix/hawtrix.git
git push -u origin main
